import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";
import {
  OPERATOR, LOCATION, CONTACT_EMAIL, MIN_AGE, GOVERNING_LAW, COURTS,
  REFUND_POLICY, PRICE_NOTICE, LIABILITY_FLOOR,
} from "@/lib/legal";

export const metadata: Metadata = {
  title: "Terms of Service — Ucorns",
  description: "The agreement between you and Ucorns, including your responsibilities when recording lectures.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="24 September 2026">
      <p>
        These terms are the agreement between you and {OPERATOR} ("Ucorns", "we", "us") for use of the
        Ucorns website and apps. By creating an account you accept them. If you do not accept them, do
        not use Ucorns.
      </p>

      <h2>1. Who can use Ucorns</h2>
      <p>
        You must be at least {MIN_AGE} years old and able to enter a contract. If you
        use Ucorns as part of study at an institution, you must also follow that institution's rules.
      </p>

      <h2>2. Recording lectures — your responsibility</h2>
      <div className="callout">
        <p>
          <strong>Ucorns gives you the means to record. It does not give you the right to record.</strong>
        </p>
        <p>
          Before recording a class you are responsible for having whatever permission the law and your
          institution require — which may mean your lecturer's consent, everyone present consenting, or
          both. Rules differ sharply between countries and between US states, and many universities
          restrict or forbid recording.
        </p>
      </div>
      <p>By recording with Ucorns you confirm that:</p>
      <ul>
        <li>you have the permission you need from the people being recorded and from your institution;</li>
        <li>you are recording for your own study, not to republish, sell or distribute;</li>
        <li>you will delete a recording if someone in it withdraws their consent.</li>
      </ul>
      <p>
        You are responsible for what you record and what you do with it. If someone brings a claim
        against us because of a recording you made, you agree to cover the costs, to the extent the law
        allows.
      </p>
      <p>
        Lecture content is usually its authors' copyright. Recording for private study is permitted in
        many places; publishing or sharing it publicly generally is not.
      </p>

      <h2>3. Your account</h2>
      <p>
        Keep your sign-in details to yourself and tell us promptly at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> if
        someone else gets into your account. One account is for one person; do not share it.
      </p>

      <h2>4. Your content</h2>
      <p>
        <strong>What you record, write and upload stays yours.</strong> You give us only the permission
        we need to run the product for you: to store your content, transcribe it, read photographs you
        take, generate study material from it, and show it back to you — and to share it with the
        processors listed in our <a href="/privacy">Privacy Policy</a> for those purposes.
      </p>
      <p>
        We do not claim ownership, we do not use your content to train models, and we do not publish it.
        The permission ends when you delete the content or your account.
      </p>
      <p>
        If you share material with another student through Ucorns, you are giving them access to it.
      </p>

      <h2>5. What Ucorns produces, and its limits</h2>
      <div className="callout">
        <p>
          <strong>Ucorns is generated by automated systems and will sometimes be wrong.</strong>{" "}
          Transcripts can mishear words. Summaries can miss things. Quiz answers, formulas and clinical
          or dosage calculations can be incorrect.
        </p>
        <p>
          Check anything that matters against your lecture, your textbook or your lecturer. Ucorns is a
          study aid — not academic, medical, clinical, legal or financial advice, and never a substitute
          for professional judgement.
        </p>
      </div>
      <p>
        You are responsible for following your institution's rules on academic honesty and the use of
        AI tools. Some institutions restrict them.
      </p>

      <h2>6. Acceptable use</h2>
      <p>Do not:</p>
      <ul>
        <li>record anyone without the permission you need;</li>
        <li>upload content you have no right to, or that is unlawful;</li>
        <li>republish or sell recordings, transcripts or material generated from someone else's teaching;</li>
        <li>harass, threaten or abuse anyone through messages or sharing;</li>
        <li>attempt to break, overload, reverse-engineer or gain unauthorised access to Ucorns;</li>
        <li>use automated means to extract data at scale, or resell access.</li>
      </ul>
      <p>We may suspend or close accounts that break these rules.</p>

      <h2>7. Plans, payment and cancellation</h2>
      <p>
        Ucorns has a free plan and paid plans. Prices and what each plan includes are shown on our{" "}
        <a href="/pricing">pricing page</a>. Paid plans are charged in full when you upgrade; there
        is no trial period.
      </p>
      <ul>
        <li><strong>Renewal.</strong> Paid plans renew automatically at the end of each period until cancelled.</li>
        <li><strong>Cancelling.</strong> Cancel at any time; you keep access until the end of the period you have paid for.</li>
        <li><strong>Refunds.</strong> {REFUND_POLICY} If you are a consumer in the EU or UK, your statutory cancellation rights still apply.</li>
        <li><strong>Price changes.</strong> We will give at least {PRICE_NOTICE} notice before a price change affects you.</li>
        <li><strong>Payment.</strong> Handled by Stripe, subject to their terms. We never see your card number.</li>
      </ul>
      <p>
        Deleting your account cancels any active subscription. We do not refund the unused part of a
        period unless the law requires it.
      </p>

      <h2>8. Plan limits</h2>
      <p>
        Plans include monthly limits on recorded audio, questions and generated material, and a maximum
        length for a single recording. Current limits are on the <a href="/pricing">pricing page</a> and
        in your account. We may change them with reasonable notice; we may also apply temporary limits
        to protect the service from abuse or unusual load.
      </p>

      <h2>9. Availability</h2>
      <p>
        We work to keep Ucorns running but do not promise it will be uninterrupted or error-free. We may
        change, suspend or discontinue features. If we discontinue Ucorns altogether, we will give you
        reasonable notice and a way to export your content.
      </p>
      <p>
        <strong>Keep your own copies of anything you cannot afford to lose.</strong> Ucorns is not a backup
        service.
      </p>

      <h2>10. Ending this agreement</h2>
      <p>
        You can stop using Ucorns and delete your account at any time from{" "}
        <strong>Account → Delete account</strong>. We may suspend or end your access if you break these
        terms, if required by law, or if we discontinue the service. Deleting your account permanently
        removes your content, as described in the <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>11. Liability</h2>
      <p>
        Nothing here limits liability that cannot be limited by law, including for death or personal
        injury caused by negligence, or for fraud.
      </p>
      <p>
        Otherwise, and to the extent the law allows: Ucorns is provided "as is"; we are not liable for
        indirect or consequential loss, lost data, lost profits, missed deadlines, or exam or academic
        outcomes; and our total liability in any twelve-month period is limited to the greater of the
        amount you paid us in that period and {LIABILITY_FLOOR}.
      </p>
      <p>
        If you are a consumer, you keep all rights the law of your country gives you, and nothing here
        takes them away.
      </p>

      <h2>12. Changes to these terms</h2>
      <p>
        We may update these terms. If a change materially affects your rights we will tell you in the
        app or by email before it takes effect. Continuing to use Ucorns after that means you accept the
        new terms.
      </p>

      <h2>13. Governing law</h2>
      <p>
        These terms are governed by the law of {GOVERNING_LAW}, and disputes will be heard by{" "}
        {COURTS}. If you are a consumer in the EU or UK, you may instead bring proceedings in your
        country of residence.
      </p>

      <h2>14. Contact</h2>
      <p>
        {OPERATOR}<br />
        {LOCATION}<br />
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
      </p>
    </LegalPage>
  );
}
